kind: Namespace
apiVersion: v1
metadata:
  name: thefirstcontainer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: merde
  labels:
    app: merde
spec:
  replicas: 1
  selector:
    matchLabels:
      app: merde
  template:
    metadata:
      labels:
        app: merde
    spec:
      containers:
      - name: merde
        image: tftest/merde
        ports:
        - containerPort: 8989
---
apiVersion: v1
kind: Service
metadata:
  name: merde
spec:
  selector:
    app: merde
  ports:
    - protocol: TCP
      port: 8989
      targetPort: 8989