apiVersion: apps/v1
kind: Deployment
metadata:
  name: merde
  labels:
    app: merde
spec:
  replicas: 3
  selector:
    matchLabels:
      app: merde
  template:
    metadata:
      labels:
        app: merde
    spec:
      containers:
      - name: merde
        image: teperwoman/merde
        ports:
        - containerPort: 8989